exp_name: viewpoint_bottleneck_scannet_ssrl
log_root_dir: logs
load:
seed: 42
dataset:
  bundle_dir: /home/aidrive/tb5zhh/vibus/SUField/bundled_datasets/SCANNET
  data_list: /home/aidrive/tb5zhh/vibus/SUField/datasets/ScanNetv2_train_data.txt
  label_list: /home/aidrive/tb5zhh/vibus/SUField/datasets/ScanNetv2_train_labels.txt
  annotate_index_dir: /home/aidrive/tb5zhh/vibus/SUField/bundled_datasets/SCANNET/limited_annotation
  split_file_dir: /home/aidrive/tb5zhh/vibus/SUField/bundled_datasets/SCANNET/split
train:
  mode: SSRL
  max_iter: 40000
  batch_size: 30
  world_size: 2
  num_workers: 4
  amp: no
  logging_steps: 1
  checkpoint_steps: 1000
  save_steps: 100
  validate_steps: 0
  limit_numpoints: 
  arch: Res16UNet34T

  annotation_count: 20
  
  transforms:
    ElasticDistortion: "[[[0.2, 0.4], [0.8, 1.6]]]"
    RandomRotation:
      "[[[-np.pi/16, -np.pi/16], [-np.pi/16, np.pi/16], [-np.pi/2, np.pi/2]]]"
    RandomScaling: "[]"
    NonNegativeTranslation: "[]"
    Voxelize: "[]"
    RandomDropout: "[0.2, 1]"
    RandomHorizontalFlip: "['z']"
    ChromaticAutoContrast: "[]"
    ChromaticTranslation: "[]"
    ChromaticJitter: "[]"
    # HueSaturationTranslation: "[0.5, 0.2]"
  
  optimizer:
    type: SGD # SGD, Adam
    learning_rate: 1.0e-3
    SGD:
      momentum: 0.9
      dampening: 0.1
      weight_decay: 1.0e-4

  scheduler:
    type: Polynomial
    poly:
      power: 0.9
validate:
  batch_size: 1
  num_workers: 1
  limit_numpoints: 
