exp_name: viewpoint_bottleneck_scannet_test
log_root_dir: logs
load:
training:
  mode: SSRL
  max_iter: 100000
  batch_size: 4
  world_size: 2
  num_workers: 2
  checkpoint_steps: 50
  validate_steps: 0
  limit_numpoints: 400000
  arch: Res16UNet34T
  dataset:
    bundle_dir: '/home/tb5zhh/SUField/bundled_datasets/SCANNET'
    data_list: /home/tb5zhh/SUField/datasets/ScanNetv2_train_data.txt
    label_list: /home/tb5zhh/SUField/datasets/ScanNetv2_train_labels.txt
  
  transforms:
    ElasticDistortion: "[[[0.2, 0.4], [0.8, 1.6]]]"
    RandomRotation:
      "[[[-np.pi/16, -np.pi/16], [-np.pi/16, np.pi/16], [-np.pi/2, np.pi/2]]]"
    RandomScaling: "[]"
    NonNegativeTranslation: "[]"
    Voxelize: "[]"
    RandomDropout: "[0.5, 1]"
    RandomHorizontalFlip: "['z']"
    ChromaticAutoContrast: "[]"
    ChromaticTranslation: "[]"
    ChromaticJitter: "[]"
    # HueSaturationTranslation: "[0.5, 0.2]"
  
  optimizer:
    type: SGD # SGD, Adam
    learning_rate: 1.0e-3
    SGD:
      momentum: 0.9
      dampening: 0.1
      weight_decay: 1.0e-4

  scheduler:
    type: Polynomial
    poly:
      power: 0.9
