training:
  max_iter: 20000
  batch_size: 4
  limit_numpoints:
  num_workers: 4
  dataset:
    data_list: /home/tb5zhh/SUField/datasets/ScanNetv2_train_data.txt
    label_list: /home/tb5zhh/SUField/datasets/ScanNetv2_train_labels.txt
  
  transforms:
    ElasticDistortion: "[[[0.2, 0.4], [0.8, 1.6]]]"
    RandomRotation:
      "[[[-np.pi/16, -np.pi/16], [-np.pi/16, np.pi/16], [-np.pi/2, np.pi/2]]]"
    RandomScaling: "[]"
    NonNegativeTranslation: "[]"
    Voxelize: "[]"
    RandomDropout: "[0.5, 1]"
    RandomHorizontalFlip: "['z']"
    ChromaticAutoContrast: "[]"
    ChromaticTranslation: "[]"
    ChromaticJitter: "[]"
    # HueSaturationTranslation: "[0.5, 0.2]"
  
  optimizer:
    type: SGD # SGD, Adam
    learning_rate: 0.01
    SGD:
      momentum: 0.9
      dampening: 0.1
      weight_decay: 1.0e-4

  scheduler:
    type: Polynomial
    poly:
      power: 0.9
