exp_name: viewpoint_bottleneck_scannet_finetune_wo_pretrain_200
log_root_dir: logs
load:
seed: 42
dataset:
  bundle_dir: /home/tb5zhh/SUField/bundled_datasets/SCANNET
  data_list: /home/tb5zhh/SUField/datasets/ScanNetv2_train_data.txt
  label_list: /home/tb5zhh/SUField/datasets/ScanNetv2_train_labels.txt
  annotate_index_dir: /home/tb5zhh/SUField/bundled_datasets/SCANNET/limited_annotation
  split_file_dir: /home/tb5zhh/SUField/bundled_datasets/SCANNET/split
train:
  mode: Finetune
  max_iter: 20000
  batch_size: 10
  world_size: 4
  num_workers: 2
  amp: yes
  logging_steps: 10
  checkpoint_steps: 1000
  save_steps: 1
  validate_steps: 100
  limit_numpoints: 400000
  arch: Res16UNet34T

  annotation_count: 200
  
  transforms:
    ElasticDistortion: "[[[0.2, 0.4], [0.8, 1.6]]]"
    RandomRotation:
      "[[[-np.pi/16, -np.pi/16], [-np.pi/16, np.pi/16], [-np.pi/2, np.pi/2]]]"
    RandomScaling: "[]"
    NonNegativeTranslation: "[]"
    Voxelize: "[]"
    RandomHorizontalFlip: "['z']"
    ChromaticAutoContrast: "[]"
    ChromaticTranslation: "[]"
    ChromaticJitter: "[]"
    # HueSaturationTranslation: "[0.5, 0.2]"
  
  optimizer:
    type: SGD # SGD, Adam
    learning_rate: 0.01
    SGD:
      momentum: 0.9
      dampening: 0.1
      weight_decay: 1.0e-4

  scheduler:
    type: Polynomial
    poly:
      power: 0.9
validate:
  batch_size: 1
  num_workers: 1
  limit_numpoints: 
  transforms:
    NonNegativeTranslation: "[]"
    Voxelize: "[]"